# Generated by Django 5.0.7 on 2025-02-04 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('delivery_name', models.CharField(max_length=50)),
                ('delivery_contact', models.CharField(max_length=15, unique=True)),
                ('delivery_address', models.TextField()),
                ('delivery_area', models.CharField(max_length=50)),
                ('delivery_image', models.ImageField(blank=True, null=True, upload_to='delivery/')),
                ('delivery_password', models.CharField(max_length=128)),
                ('delivery_registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_last_login', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Delivery Person',
                'verbose_name_plural': 'Delivery Persons',
                'ordering': ['-delivery_registered_at'],
            },
        ),
    ]
