# Generated by Django 5.0.7 on 2025-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
