# Generated by Django 5.0.7 on 2025-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryorder_items_deliveryorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
