# Generated by Django 5.0.7 on 2025-02-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryperson_total_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='total_earnings',
        ),
    ]
