# Generated by Django 5.0.7 on 2024-08-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_car_product_car_name_product_speed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='car',
        ),
    ]
