# Generated by Django 5.0.7 on 2024-12-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department']},
        ),
    ]
