# Generated by Django 5.0.7 on 2025-02-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
    ]
