# Generated by Django 5.0.7 on 2025-01-24 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=50, verbose_name='Kitchen Name')),
                ('kitchen_description', models.TextField(max_length=255, verbose_name='Kitchen Description')),
                ('kitchen_address', models.TextField(verbose_name='Kitchen Address')),
                ('kitchen_place', models.CharField(max_length=50, verbose_name='Kitchen Landmark')),
                ('kitchen_image', models.ImageField(blank=True, null=True, upload_to='kitchen', verbose_name='Kitchen Image')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('kitchen_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('kitchen_is_verified', models.BooleanField(default=False, verbose_name='Verified Kitchen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitchen Information',
                'verbose_name_plural': 'Kitchen Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
