# Generated by Django 5.0.7 on 2025-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_remove_kitcheninfo_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcheninfo',
            name='kitchen_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
