# Generated by Django 5.0.7 on 2025-01-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_remove_kitcheninfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitcheninfo',
            name='kitchen_password',
            field=models.CharField(max_length=128),
        ),
    ]
