# Generated by Django 5.0.7 on 2025-01-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_alter_kitcheninfo_kitchen_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcheninfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
