# Generated by Django 5.0.7 on 2025-01-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_kitcheninfo_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcheninfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
