# Generated by Django 5.0.7 on 2025-01-28 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_kitcheninfo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_description', models.TextField()),
                ('recipe_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipe_rating', models.FloatField()),
                ('preparation_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='kitcheninfo',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='kitchen/'),
        ),
    ]
