# Generated by Django 5.0.7 on 2025-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_alter_kitchenrecipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenrecipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
