# Generated by Django 5.0.7 on 2025-02-02 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_kitchenrecipe_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_description', models.TextField()),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_rating', models.FloatField(default=0.0)),
                ('preparation_time', models.PositiveIntegerField(default=30)),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_available', models.BooleanField(default=True)),
                ('kitchen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='kitchen.kitcheninfo')),
            ],
            options={
                'verbose_name': 'Kitchen Dish',
                'verbose_name_plural': 'Kitchen Dishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='KitchenRecipe',
        ),
    ]
