# Generated by Django 5.0.7 on 2025-02-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_kitchendish_delete_kitchenrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchendish',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='kitchen.kitcheninfo'),
        ),
    ]
