# Generated by Django 5.0.7 on 2025-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_alter_kitchendish_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcheninfo',
            name='kitchen_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
